### ISSUE TITLE
segmentation fault / core dump, on STAR or BWA MEM bam files

### ISSUE THREAD

**Issue by jfass** [Kingsford-Group/diploidsquid#2]
I previously ran Squid on BWA MEM bam files, with no problems, on certain datasets in ~2019. Now I'm trying to extend that work by running Squid on GTEX datasets (and unfortunately I can't share any of those data). But now I'm getting this:

```     6 Segmentation fault      (core dumped) /opt/diploidsquid -b /home/squid/${id}_Aligned.sortedByCoord.out.bam -c /home/squid/${id}_Chimeric.out.bam -o /home/squid/${id}```

This happens after reading in the chimeric BAM:

```[...]
Reference name chrUn_gl000247   -->     90
Reference name chrUn_gl000248   -->     91
Reference name chrUn_gl000249   -->     92
Reference name chrX     -->     23
Reference name chrY     -->     24
[Fri May 14 17:55:21 2021] Start reading bam file.
[Fri May 14 17:55:34 2021] Finish sorting Chimeric bam reads.
[Fri May 14 17:55:37 2021] Finish removing PCR duplicates.
[Fri May 14 17:55:39 2021] Building nodes. |bamdiscordant|=914809
[Fri May 14 17:58:44 2021] Building nodes, finish seeding.
```

... and it happens with the current Squid binary, the 1.5 binary, when I build Squid from the current repo, or the 1.5 sources, and when I build the 1.0 DiploidSquid. I've tried BWA MEM output from various BWA / SAMTools versions, STAR two-pass alignments, STAR one-pass alignments, turning off all but the --ChimOutType and --ChimSegMin options, re-sorting the STAR BAM with SAMTools, coordinate sorting the chimeric BAM ... and some other things I'm probably forgetting.

I'm using STAR 2.5.3a, I think ... and I'm going to try a more recent STAR, but I'd prefer to stick with 2.5.3 due to having lots of results already, but I can update if I need to.

I guess my general question is: are you guys familiar with this kind of behavior? There are a couple issues on the Squid repo that suggest others have seen it, but one of those issues is closed with the comment that a more recent commit should have fixed it. Are there any variables I'm not thinking of? STAR version, of course, but maybe parameters affecting SAM attributes? Reference issues?

Please let me know ... thanks!

**Comment by ckingsford** [comment]
Hi! Thanks for the question/issue report. We're not sure what is going on yet. Would it be possible for you to send us:
* (a) the complete stdout log of squid to double-check whether we locate the error correctly, 
* (b) the specific STAR command you used to create the BAMs, 
* (c) whether there is any post-STAR processing steps/commands, 
* (d) output of `samtools view -H /home/squid/${id}_Aligned.sortedByCoord.out.bam` and `samtools view -H /home/squid/${id}_Chimeric.out.bam` to check the reference information in the header.

**Comment by jfass** [comment]
Hey - thanks for the response. Let's see ...

(a) stdout is:
```Reference name chr1     -->     0
Reference name chr10    -->     9
Reference name chr11    -->     10
Reference name chr12    -->     11
Reference name chr13    -->     12
Reference name chr14    -->     13
Reference name chr15    -->     14
Reference name chr16    -->     15
Reference name chr17    -->     16
Reference name chr18    -->     17
Reference name chr19    -->     18
Reference name chr2     -->     1
Reference name chr20    -->     19
Reference name chr21    -->     20
Reference name chr22    -->     21
Reference name chr3     -->     2
Reference name chr4     -->     3
Reference name chr5     -->     4
Reference name chr6     -->     5
Reference name chr7     -->     6
Reference name chr8     -->     7
Reference name chr9     -->     8
Reference name chrM     -->     24
Reference name chrX     -->     22
Reference name chrY     -->     23
[Thu May 27 17:25:31 2021] Start reading bam file.
[Thu May 27 17:25:45 2021] Finish sorting Chimeric bam reads.
[Thu May 27 17:25:47 2021] Finish removing PCR duplicates.
[Thu May 27 17:25:49 2021] Building nodes. |bamdiscordant|=967946
[Thu May 27 17:29:12 2021] Building nodes, finish seeding.
```
... and stderr is:
```/opt/squid.sh: line 9:     6 Segmentation fault      (core dumped) /opt/diploidsquid -b /home/squid/${id}_Aligned.sortedByCoord.out.bam -c /home/squid/${id}_Chimeric.out.bam -o /home/squid/${id}
Traceback (most recent call last):
  File "/opt/AnnotateSQUIDOutput.py", line 336, in <module>
    Annotate(SquidPrediction, OutputFile, glocater, Transcripts, GeneTransMap)
  File "/opt/AnnotateSQUIDOutput.py", line 243, in Annotate
    fpin = open(insquidfile, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/squid/GTEX-SNOS-0926-SM-4DM7A_sv.txt'
```
(the first line is obviously the problem, and the rest just a consequence of the annotation script not finding the squid output file)
(b) I've run various versions (2.5.3a?, 2.7.9a) of STAR, with various settings (twopass, single pass, more chimera options, etc.) in docker containers or conda environments ... here's the latest docker command:
```docker run --rm     -v /home/jfass/GTEx_RNA-Seq_panel:/home/ubuntu/GTEx_RNA-Seq_panel     -v /home/jfass/GTEx_RNA-Seq_panel/REF:/tmp/References/STAR_genome     -w /home/ubuntu/GTEx_RNA-Seq_panel/${id}.squid.out     rna-star --genomeDir /tmp/References/STAR_genome     --readFilesIn /home/ubuntu/GTEx_RNA-Seq_panel/${id}.squid.out/${id}_R1.fastq.gz /home/ubuntu/GTEx_RNA-Seq_panel/${id}.squid.out/${id}_R2.fastq.gz     --outSAMattrRGline ID:${id} --readFilesCommand zcat --outFileNamePrefix /home/ubuntu/GTEx_RNA-Seq_panel/${id}.squid.out/${id}_     --outSAMtype BAM SortedByCoordinate --outSAMmapqUnique 60 --runThreadN 6 --outSAMunmapped Within --limitBAMsortRAM 160000000000     --chimOutType SeparateSAMold --chimSegmentMin 15```
... the input fastq's are from downloaded GTEX BAM files that I've run picard SamToFastq on ... and I can't find anything suspicious about them.
(c) After STAR I just view the chimera SAM file to a BAM, and index both it and the main STAR BAM with samtools
(d) headers are attached for the main STAR "Aligned.sortedByCoord" file ("AH.txt") and the Chimeric BAM file ("CH.txt")
[AH.txt](https://github.com/Kingsford-Group/diploidsquid/files/6555725/AH.txt)
[CH.txt](https://github.com/Kingsford-Group/diploidsquid/files/6555727/CH.txt)

One other thing to mention: whenever I run 'squid --help', however I've installed it, I see it spit out maybe a dozen usage messages, one after another. Is this just a consequence of a wrapper script around the main binary? Or could this indicate that something in the way I've set up any of my environments isn't correct? As far as I recall, it does this when I build it, or using your binaries, or using the conda package, etc.

Many thanks for looking into this!
